apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    command: [ "/bin/sh", "-c", "--" ] 
    args: [ "while true; do sleep 30; done;" ]
#     args: ["--context=git://github.com/azattar/k8s_jupyterlab.git",
#             "--dockerfile=/Dockerfile",
#             "--destination=<<TOKEN>>/registry.digitalocean.com/k8s-01-registry"] # replace with your dockerhub account
#    args: ["--dockerfile=/workspace/dockerfile",
#            "--context=dir://workspace",
#            "--destination=<user-name>/<repo>"] # replace with your dockerhub account
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
      - name: dockerfile-storage
        mountPath: /workspace
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: dockerfile-storage
      persistentVolumeClaim:
        claimName: dockerfile-claim
