# kubectl create secret docker-registry regcred \
# --docker-server=registry.digitalocean.com/k8s-01-registry \
# --docker-username=xxxx \
# --docker-password=xxxx \
# --docker-email=azattar@gmail.com
apiVersion: v1
data:
  .dockerconfigjson: xxx
kind: Secret
metadata:
  name: regcred
  namespace: default
type: kubernetes.io/dockerconfigjson
